export type Template = {
  id: string;
  frameworkId: string;
  name: string;
  description: string;
  body: string;
};

export const templates: Template[] = [
  {
    id: "owasp_simple",
    frameworkId: "owasp_top10_2021",
    name: "OWASP – Executive Summary",
    description: "Short executive-style report for OWASP Top 10",
    body: `
# VAPT Report – {{projectName}}

Client: **{{clientName}}**  
Engagement Date: **{{date}}**  
Framework: **{{frameworkName}}**

---

## 1. Overview

This assessment was conducted using the **{{frameworkName}}** framework to evaluate the security posture of the target applications.

## 2. Scope

- Targets: {{scope}}
- Testing Type: {{testingType}}
- Methodology: {{methodology}}

## 3. Summary of Findings

Total Findings: **{{findingsCount}}**  
Critical: **{{criticalCount}}**, High: **{{highCount}}**, Medium: **{{mediumCount}}**, Low: **{{lowCount}}**

---

## 4. Findings Details

{{findingsBlock}}

## 5. Overall Risk Rating

Overall Risk: **{{overallRisk}}**

## 6. Remediation Roadmap

{{remediationRoadmap}}

---

_This report is generated automatically by VulnBoard (white-label ready)._
`
  },
  {
    id: "pci_detailed",
    frameworkId: "pci_dss_4",
    name: "PCI DSS – Technical Report",
    description: "Technical-style report for PCI DSS",
    body: `
# PCI DSS Technical VAPT Report – {{projectName}}

Client: **{{clientName}}**  
Framework: **{{frameworkName}} v{{frameworkVersion}}**

## 1. Executive Summary
{{executiveSummary}}

## 2. PCI DSS Control Coverage

{{gapSummary}}

## 3. Detailed Findings

{{findingsBlock}}

## 4. Compliance Gap Summary

{{gapSummary}}

---
Generated by VulnBoard – VAPT Dashboard Management.
`
  }
];
