export type Template = {
  id: string;
  frameworkId: string;
  name: string;
  description: string;
  language: 'en' | 'id';
  body: string;
};

export const templates: Template[] = [
  {
    id: "owasp_executive_en",
    frameworkId: "owasp_top10_2021",
    name: "OWASP Executive Summary",
    description: "High-level executive summary report based on OWASP Top 10 2021",
    language: "en",
    body: `# Executive Summary — {{projectName}}

**Client:** {{clientName}}
**Date:** {{date}}
**Framework:** {{frameworkName}} {{frameworkVersion}}

---

## 1. Engagement Overview

A security assessment was conducted for **{{clientName}}** targeting the application **{{projectName}}**. This assessment followed the **{{frameworkName}}** framework to identify and categorize key web application security risks.

**Scope:** {{scope}}
**Testing Type:** {{testingType}}

## 2. Summary of Findings

| Severity | Count |
|----------|-------|
| Critical | {{criticalCount}} |
| High     | {{highCount}} |
| Medium   | {{mediumCount}} |
| Low      | {{lowCount}} |
| **Total** | **{{findingsCount}}** |

**Overall Risk Rating:** {{overallRisk}}

## 3. Key Observations

The assessment revealed {{findingsCount}} findings. The overall risk posture has been assessed as **{{overallRisk}}** based on the number and severity of discovered vulnerabilities.

## 4. Remediation Roadmap

{{remediationRoadmap}}

## 5. Conclusion

Immediate remediation of Critical and High severity findings is recommended. A re-assessment should be scheduled post-remediation to verify fixes.

---
_Generated by VulnBoard — VAPT Dashboard Management_`
  },
  {
    id: "owasp_executive_id",
    frameworkId: "owasp_top10_2021",
    name: "OWASP Ringkasan Eksekutif",
    description: "Laporan ringkasan eksekutif berdasarkan OWASP Top 10 2021",
    language: "id",
    body: `# Ringkasan Eksekutif — {{projectName}}

**Klien:** {{clientName}}
**Tanggal:** {{date}}
**Framework:** {{frameworkName}} {{frameworkVersion}}

---

## 1. Gambaran Umum

Penilaian keamanan telah dilakukan untuk **{{clientName}}** pada aplikasi **{{projectName}}**. Penilaian ini mengikuti framework **{{frameworkName}}** untuk mengidentifikasi dan mengkategorikan risiko keamanan aplikasi web.

**Cakupan:** {{scope}}
**Jenis Pengujian:** {{testingType}}

## 2. Ringkasan Temuan

| Tingkat Keparahan | Jumlah |
|-------------------|--------|
| Critical | {{criticalCount}} |
| High     | {{highCount}} |
| Medium   | {{mediumCount}} |
| Low      | {{lowCount}} |
| **Total** | **{{findingsCount}}** |

**Peringkat Risiko Keseluruhan:** {{overallRisk}}

## 3. Observasi Utama

Penilaian ini mengungkap {{findingsCount}} temuan. Postur risiko keseluruhan dinilai **{{overallRisk}}** berdasarkan jumlah dan tingkat keparahan kerentanan yang ditemukan.

## 4. Peta Jalan Remediasi

{{remediationRoadmap}}

## 5. Kesimpulan

Remediasi segera untuk temuan Critical dan High sangat disarankan. Penilaian ulang harus dijadwalkan setelah remediasi untuk memverifikasi perbaikan.

---
_Dibuat oleh VulnBoard — Manajemen Dashboard VAPT_`
  },
  {
    id: "owasp_technical_en",
    frameworkId: "owasp_top10_2021",
    name: "OWASP Technical Detailed Report",
    description: "Comprehensive technical vulnerability assessment report using OWASP Top 10 2021",
    language: "en",
    body: `# Technical Vulnerability Assessment Report — {{projectName}}

**Client:** {{clientName}}
**Date:** {{date}}
**Framework:** {{frameworkName}} {{frameworkVersion}}

---

## 1. Introduction

This document provides the technical findings from the security assessment of **{{projectName}}** for **{{clientName}}**. The assessment was performed in accordance with the **{{frameworkName}}** framework.

## 2. Scope & Methodology

**Scope:** {{scope}}
**Testing Type:** {{testingType}}
**Methodology:** {{methodology}}

## 3. Findings Summary

| Severity | Count |
|----------|-------|
| Critical | {{criticalCount}} |
| High     | {{highCount}} |
| Medium   | {{mediumCount}} |
| Low      | {{lowCount}} |
| **Total** | **{{findingsCount}}** |

**Overall Risk Rating:** {{overallRisk}}

## 4. Detailed Findings

{{findingsBlock}}

## 5. Risk Analysis

The overall risk is rated as **{{overallRisk}}**. Findings mapped to the {{frameworkName}} categories show the most impactful issues in injection and access control domains.

## 6. Remediation Roadmap

{{remediationRoadmap}}

## 7. Appendix

- Testing tools and versions used
- Evidence screenshots referenced in findings
- CVSS scoring methodology

---
_Generated by VulnBoard — VAPT Dashboard Management_`
  },
  {
    id: "owasp_technical_id",
    frameworkId: "owasp_top10_2021",
    name: "OWASP Laporan Teknis Detail",
    description: "Laporan teknis penilaian kerentanan menggunakan OWASP Top 10 2021",
    language: "id",
    body: `# Laporan Teknis Penilaian Kerentanan — {{projectName}}

**Klien:** {{clientName}}
**Tanggal:** {{date}}
**Framework:** {{frameworkName}} {{frameworkVersion}}

---

## 1. Pendahuluan

Dokumen ini menyajikan temuan teknis dari penilaian keamanan **{{projectName}}** untuk **{{clientName}}**. Penilaian dilakukan sesuai dengan framework **{{frameworkName}}**.

## 2. Cakupan & Metodologi

**Cakupan:** {{scope}}
**Jenis Pengujian:** {{testingType}}
**Metodologi:** {{methodology}}

## 3. Ringkasan Temuan

| Tingkat Keparahan | Jumlah |
|-------------------|--------|
| Critical | {{criticalCount}} |
| High     | {{highCount}} |
| Medium   | {{mediumCount}} |
| Low      | {{lowCount}} |
| **Total** | **{{findingsCount}}** |

**Peringkat Risiko Keseluruhan:** {{overallRisk}}

## 4. Detail Temuan

{{findingsBlock}}

## 5. Analisis Risiko

Risiko keseluruhan dinilai **{{overallRisk}}**. Temuan yang dipetakan ke kategori {{frameworkName}} menunjukkan isu paling berdampak pada domain injeksi dan kontrol akses.

## 6. Peta Jalan Remediasi

{{remediationRoadmap}}

## 7. Lampiran

- Alat dan versi pengujian yang digunakan
- Tangkapan layar bukti yang direferensikan dalam temuan
- Metodologi penilaian CVSS

---
_Dibuat oleh VulnBoard — Manajemen Dashboard VAPT_`
  },
  {
    id: "nist_csf_en",
    frameworkId: "nist_csf_2",
    name: "NIST CSF Assessment Report",
    description: "Cybersecurity assessment report based on NIST Cybersecurity Framework 2.0",
    language: "en",
    body: `# NIST CSF 2.0 Assessment Report — {{projectName}}

**Client:** {{clientName}}
**Date:** {{date}}
**Framework:** {{frameworkName}} {{frameworkVersion}}

---

## 1. Executive Summary

This report summarizes the cybersecurity posture assessment of **{{projectName}}** for **{{clientName}}**, evaluated against the six core functions of the **{{frameworkName}} {{frameworkVersion}}**: Govern, Identify, Protect, Detect, Respond, and Recover.

**Scope:** {{scope}}
**Testing Type:** {{testingType}}

## 2. Methodology

{{methodology}}

## 3. Findings Overview

| Severity | Count |
|----------|-------|
| Critical | {{criticalCount}} |
| High     | {{highCount}} |
| Medium   | {{mediumCount}} |
| Low      | {{lowCount}} |
| **Total** | **{{findingsCount}}** |

**Overall Risk Rating:** {{overallRisk}}

## 4. Findings by CSF Function

{{findingsBlock}}

## 5. Gap Analysis & Maturity Assessment

The organization demonstrates gaps across the six CSF functions. Priority should be given to the Protect and Detect functions where the most significant deficiencies were observed.

## 6. Remediation Roadmap

{{remediationRoadmap}}

## 7. Recommendations

- Establish formal governance (GV) policies
- Enhance continuous monitoring capabilities (DE)
- Develop and test incident response and recovery playbooks (RS/RC)

---
_Generated by VulnBoard — VAPT Dashboard Management_`
  },
  {
    id: "iso27001_en",
    frameworkId: "iso27001_2022",
    name: "ISO 27001 Gap Assessment Report",
    description: "ISO/IEC 27001:2022 Annex A gap assessment report",
    language: "en",
    body: `# ISO/IEC 27001:2022 Gap Assessment Report — {{projectName}}

**Client:** {{clientName}}
**Date:** {{date}}
**Framework:** {{frameworkName}} {{frameworkVersion}}

---

## 1. Executive Summary

A gap assessment was conducted for **{{clientName}}** to evaluate compliance with **{{frameworkName}} {{frameworkVersion}}** Annex A controls. This report identifies areas of non-conformity and provides a prioritized remediation plan.

**Scope:** {{scope}}
**Testing Type:** {{testingType}}

## 2. Methodology

{{methodology}}

## 3. Summary of Non-conformities

| Severity | Count |
|----------|-------|
| Critical | {{criticalCount}} |
| High     | {{highCount}} |
| Medium   | {{mediumCount}} |
| Low      | {{lowCount}} |
| **Total** | **{{findingsCount}}** |

**Overall Risk Rating:** {{overallRisk}}

## 4. Detailed Findings by Control Domain

### 4.1 Organizational Controls (Clause 5)
### 4.2 People Controls (Clause 6)
### 4.3 Physical Controls (Clause 7)
### 4.4 Technological Controls (Clause 8)

{{findingsBlock}}

## 5. Remediation Roadmap

{{remediationRoadmap}}

## 6. Conclusion

The assessment revealed {{findingsCount}} gaps against ISO 27001:2022 Annex A. Achieving certification readiness requires addressing all Critical and High findings within the remediation timeline.

---
_Generated by VulnBoard — VAPT Dashboard Management_`
  },
  {
    id: "pci_dss_technical_en",
    frameworkId: "pci_dss_4",
    name: "PCI DSS Technical Report",
    description: "PCI DSS v4.0 technical compliance and vulnerability assessment report",
    language: "en",
    body: `# PCI DSS v4.0 Technical Compliance Report — {{projectName}}

**Client:** {{clientName}}
**Date:** {{date}}
**Framework:** {{frameworkName}} {{frameworkVersion}}

---

## 1. Executive Summary

A technical security assessment was performed for **{{clientName}}** to evaluate compliance with **{{frameworkName}} {{frameworkVersion}}**. The assessment covered all 12 requirements with focus on the cardholder data environment (CDE).

**Scope:** {{scope}}
**Testing Type:** {{testingType}}

## 2. Methodology

{{methodology}}

## 3. Summary of Findings

| Severity | Count |
|----------|-------|
| Critical | {{criticalCount}} |
| High     | {{highCount}} |
| Medium   | {{mediumCount}} |
| Low      | {{lowCount}} |
| **Total** | **{{findingsCount}}** |

**Overall Risk Rating:** {{overallRisk}}

## 4. Requirement Coverage & Findings

{{findingsBlock}}

## 5. Compliance Status

Non-compliant requirements must be addressed before the next scheduled assessment. All Critical and High findings represent potential compliance failures that could impact PCI DSS certification.

## 6. Remediation Roadmap

{{remediationRoadmap}}

## 7. Conclusion

Immediate action is required for {{criticalCount}} critical and {{highCount}} high severity findings to maintain PCI DSS compliance.

---
_Generated by VulnBoard — VAPT Dashboard Management_`
  },
  {
    id: "pentest_full_en",
    frameworkId: "owasp_top10_2021",
    name: "Full Penetration Test Report",
    description: "Comprehensive penetration test report with methodology, attack narrative, and CVSS scoring",
    language: "en",
    body: `# Penetration Test Report — {{projectName}}

**Client:** {{clientName}}
**Date:** {{date}}
**Framework:** {{frameworkName}} {{frameworkVersion}}

---

## 1. Executive Summary

A penetration test was conducted for **{{clientName}}** on the target application/system **{{projectName}}**. The engagement aimed to identify exploitable vulnerabilities and demonstrate potential business impact through controlled exploitation.

**Overall Risk Rating:** {{overallRisk}}
**Total Findings:** {{findingsCount}}

## 2. Scope & Rules of Engagement

**In-Scope Targets:** {{scope}}
**Testing Type:** {{testingType}}
**Testing Window:** {{date}}

### 2.1 Out-of-Scope
- Denial of Service (DoS) attacks
- Social engineering of client employees
- Physical security testing (unless explicitly authorized)

## 3. Methodology

{{methodology}}

### 3.1 Phases
1. **Reconnaissance** — Passive and active information gathering
2. **Enumeration** — Service discovery, port scanning, technology fingerprinting
3. **Vulnerability Analysis** — Automated scanning and manual testing
4. **Exploitation** — Controlled exploitation of confirmed vulnerabilities
5. **Post-Exploitation** — Privilege escalation, lateral movement, data access
6. **Reporting** — Documentation of findings with evidence and remediation

## 4. Findings Summary

| Severity | Count |
|----------|-------|
| Critical | {{criticalCount}} |
| High     | {{highCount}} |
| Medium   | {{mediumCount}} |
| Low      | {{lowCount}} |
| **Total** | **{{findingsCount}}** |

### CVSS Score Distribution

| Finding | CVSS Score | Severity | Status |
|---------|-----------|----------|--------|
| *(populated from findings)* | | | |

## 5. Attack Narrative

This section provides a walkthrough of the attack path followed during the engagement, describing how vulnerabilities were chained to achieve significant access or impact.

*(Attack narrative details populated per engagement)*

## 6. Detailed Findings

{{findingsBlock}}

## 7. Remediation Roadmap

{{remediationRoadmap}}

## 8. Conclusion

The penetration test revealed {{findingsCount}} vulnerabilities, including {{criticalCount}} critical and {{highCount}} high severity issues. The overall risk posture is **{{overallRisk}}**. Immediate remediation of critical findings is required.

## 9. Appendix

- A. Tools Used
- B. Evidence & Screenshots
- C. CVSS v3.1 Scoring Reference
- D. Disclosure Timeline

---
_Generated by VulnBoard — VAPT Dashboard Management_`
  },
];
